directory_path: "travail/projet-ml-moteur-identification-gaia/confidentiel/personnel_non_sensible"
input_path: "test_decoupe.csv"
sep: ","
encodeur: "utf-8"
vars_names_nom_voie: ["type_voie", "nom_voie"]
plateform: "ls3"
