directory_path: "travail/projet-ml-moteur-identification-gaia/confidentiel/personnel_non_sensible"
input_path: "2022_06_01_RCA.csv"
sep: ";"
encodeur: "utf-8"
vars_names_nom_voie: ["denomination_de_voie_type", "denomination_de_voie_libelle"]
plateform: "ls3"