directory_path: "travail/projet-ml-moteur-identification-gaia/confidentiel/personnel_non_sensible"
input_path: "majic_2025"
sep: ";"
encodeur: "utf-8"
vars_names_nom_voie: ["dvoilib"]
plateform: "ls3"