new_lib_for_existing_codes = {'ZA': "ZONE D'ACTIVITES",
                              'ZAC': "ZONE D'AMENAGEMENT CONCERTE",
                              'ZAD': "ZONE D'AMENAGEMENT DIFFERE",
                              'ZI': 'ZONE INDUSTRIELLE',
                              'ZUP': 'ZONE A URBANISER EN PRIORITE'}
new_codes = [{'CODE': 'ZAE',
             'LIBELLE': "ZONE D'ACTIVITES ECONOMIQUES"},
             {'CODE': 'GRA',
             'LIBELLE': "GRANDE ALLEE"},
             {'CODE': 'APL',
             'LIBELLE': "ANCIENNE PLACE"},
             {'CODE': 'ANV',
             'LIBELLE': "ANCIENNE VOIE"},]

other_spelling_for_codes = [{'CODE': 'CHP', 'LIBELLE': 'CHAMPS'},
                            {'CODE': 'GR', 'LIBELLE': 'GDE RUE'},
                            {'CODE': 'ACH', 'LIBELLE': "ANCIEN CHEM"},
                            {'CODE': 'ACH', 'LIBELLE': "ANC CHEM"},
                            {'CODE': 'ART', 'LIBELLE': "ANC RTE"},
                            {'CODE': 'ACH', 'LIBELLE': 'ANC CHEMIN'},
                            {'CODE': 'VCHE', 'LIBELLE': 'VX CHEMIN'},
                            {'CODE': 'VCHE', 'LIBELLE': 'VX CHE'},
                            {'CODE': 'VCHE', 'LIBELLE': 'VX CHEM'},
                            {'CODE': 'ART', 'LIBELLE': 'ANC ROUTE'},
                            {'CODE': 'PCH', 'LIBELLE': 'PT CHEM'},
                            {'CODE': 'ZAE', 'LIBELLE': "ZONE D'ACTIVITES ECONOMIQUES"},
                            {'CODE': 'ZA', 'LIBELLE': "PARC D'ACTIVITES"},
                            {'CODE': 'AV', 'LIBELLE': "AVE"},
                            {'CODE': 'PTR', 'LIBELLE': "PTE RUE"},
                            {'CODE': 'VGE', 'LIBELLE': "VILLAG"},
                            {'CODE': 'GRA', 'LIBELLE': "GDE ALLEE"},
                            {'CODE': 'APL', 'LIBELLE': "ANC PL"},
                            {'CODE': 'ANV', 'LIBELLE': "ANC VOIE"},]

combinaisons_long = {'CHEMIN/VOIE COMMUNALE': True,
                'VOIE/RUE': False,
                'IMPASSE/VOIE': True,
                'IMPASSE/PLACE': False,
                'CHEMIN/ALLEE': True,
                'VOIE COMMUNALE/ROUTE': False,
                'VOIE/VOIE COMMUNALE': True,
                'VOIE COMMUNALE/CHEMIN': False,
                'CHEMINEMENT/CHEMIN': False,
                'CHEMIN/CHEMINEMENT': True,
                'VOIE COMMUNALE/AVENUE': False,
                'IMPASSE/ROUTE': False,
                'VOIE COMMUNALE/BOULEVARD': False,
                'IMPASSE/CHEMIN': False,
                'RUE/ROUTE': True,
                'ALLEE/VOIE COMMUNALE': True,
                'ROUTE/VOIE COMMUNALE': True,
                'PLACE/RUE': False,
                'RUE/IMPASSE': True,
                'RUE/VOIE COMMUNALE': True,
                'RUE/CHEMIN': True,
                'RUE/VOIE': True,
                'ROUTE/RUE': False,
                'IMPASSE/RUE': False,
                'CHEMIN/ROUTE': False,
                'IMPASSE/CHEMINEMENT': True,
                'IMPASSE/BOULEVARD': False,
                'AVENUE/VOIE COMMUNALE': True,
                'RUE/AVENUE': False,
                'VOIE COMMUNALE/IMPASSE': False,
                'ALLEE/RUE': False,
                'ROUTE/VOIE': True,
                'AVENUE/IMPASSE': True,
                'ROUTE/CHEMINEMENT': True,
                'ROUTE/CHEMIN': True,
                'PLACE/ROUTE': True,
                'IMPASSE/AVENUE': False,
                'CHEMINEMENT/VOIE COMMUNALE': True,
                'RUE/ALLEE': True,
                'RUE/CHEMINEMENT': True,
                'CHEMIN/RUE': False,
                'BOULEVARD/VOIE COMMUNALE': True,
                'CHEMINEMENT/RUE': False,
                'IMPASSE/VOIE COMMUNALE': True,
                'RUE/PLACE': True,
                'VOIE COMMUNALE/RUE': False,
                'VOIE COMMUNALE/VOIE': False,
                'VOIE COMMUNALE/CHEMINEMENT': False,
                'VOIE COMMUNALE/ALLEE': False,
                'CHEMINEMENT/VOIE': True,
                'CHEMINEMENT/ROUTE': False,
                'CHEMIN/AVENUE': False,
                'CHEMIN/VOIE': True,
                'CHEMIN/CHEMINEMENT': True,
                'AVENUE/PLACE': True,
                'AVENUE/CHEMINEMENT': True,}
